[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  GEMINI_API_KEY = "AIzaSyBQboyVKlOf2qDV9XqGHDaa-sugLKiRILg"
  VITE_GEMINI_API_KEY = "AIzaSyBQboyVKlOf2qDV9XqGHDaa-sugLKiRILg"
  VITE_FIREBASE_PROJECT_ID = "calert-h175v"
  VITE_GOOGLE_CLIENT_ID_WEB = "360373462324-nr5vpdjfd1g5i38j5h5c6l3g74d0lqd9.apps.googleusercontent.com"
  VITE_GOOGLE_CLIENT_ID_EXTENSION = "360373462324-0fjqvtd35esaqi5v8ioschmbhshj0l4l.apps.googleusercontent.com"
  VITE_SERVER_BASE_URL = "https://calert-360373462324.us-west1.run.app"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://accounts.google.com https://apis.google.com; style-src 'self' 'unsafe-inline' https://accounts.google.com; connect-src 'self' https://accounts.google.com https://www.googleapis.com https://calert-360373462324.us-west1.run.app; frame-src https://accounts.google.com; img-src 'self' data: https:;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200