name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          # Not required for build but available if needed by Vite define
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Package Chrome Extension
        run: npm run package-extension

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: calert-extension
          path: calert-extension-v*.zip
